/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetrieveRouteImport } from './routes/retrieve'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as FallbackRouteImport } from './routes/fallback'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CorpusRouteImport } from './routes/corpus'
import { Route as IndexRouteImport } from './routes/index'

const RetrieveRoute = RetrieveRouteImport.update({
  id: '/retrieve',
  path: '/retrieve',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const FallbackRoute = FallbackRouteImport.update({
  id: '/fallback',
  path: '/fallback',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusRoute = CorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/documents': typeof DocumentsRoute
  '/fallback': typeof FallbackRoute
  '/ingest': typeof IngestRoute
  '/retrieve': typeof RetrieveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/documents': typeof DocumentsRoute
  '/fallback': typeof FallbackRoute
  '/ingest': typeof IngestRoute
  '/retrieve': typeof RetrieveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/documents': typeof DocumentsRoute
  '/fallback': typeof FallbackRoute
  '/ingest': typeof IngestRoute
  '/retrieve': typeof RetrieveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corpus'
    | '/documents'
    | '/fallback'
    | '/ingest'
    | '/retrieve'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/corpus' | '/documents' | '/fallback' | '/ingest' | '/retrieve'
  id:
    | '__root__'
    | '/'
    | '/corpus'
    | '/documents'
    | '/fallback'
    | '/ingest'
    | '/retrieve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorpusRoute: typeof CorpusRoute
  DocumentsRoute: typeof DocumentsRoute
  FallbackRoute: typeof FallbackRoute
  IngestRoute: typeof IngestRoute
  RetrieveRoute: typeof RetrieveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retrieve': {
      id: '/retrieve'
      path: '/retrieve'
      fullPath: '/retrieve'
      preLoaderRoute: typeof RetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallback': {
      id: '/fallback'
      path: '/fallback'
      fullPath: '/fallback'
      preLoaderRoute: typeof FallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus': {
      id: '/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof CorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorpusRoute: CorpusRoute,
  DocumentsRoute: DocumentsRoute,
  FallbackRoute: FallbackRoute,
  IngestRoute: IngestRoute,
  RetrieveRoute: RetrieveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
